services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 5mtech-ai:v3

    ports:
      - "5000:5000"

    env_file:
      - .env

    environment:
      DATA_DIR: /app/data

    volumes:
      - fivemtech_data:/app/data

volumes:
  fivemtech_data: